mongodb/docs-mongodb-vscode

source/includes/steps-install-vsce.yaml, source/install.txt
Adding info on how to obtain the Visual Studio Code Extension.
A note: When this is available in the marketplace, I'll add a screenshot to step 1 to help users ensure they're installing the correct extension. Since it's not available on the marketplace yet, we can't grab a screenshot.
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/fea4189/mongodb-vscode/docsworker/DOCSP-9710/install
=> (DOCSP-9710): Install VSCE

source/connect.txt, source/crud-ops.txt, source/databases-collections.txt, source/includes/fact-vsce-preview.rst, source/index.txt, source/install.txt, source/playgrounds.txt, source/run-agg-pipelines.txt, source/settings.txt
Adding a banner indicating that this is a Preview extension. The content is single-sourced on each page.
Staged: [Index](https://docs-mongodbcom-staging.corp.mongodb.com/f9a4cd6/mongodb-vscode/docsworker/DOCSP-10287/)
=> (DOCSP-10287): Add Preview banner

source/commands.txt
Add Reference page for all available Commands for VSCE. 
A note for review, we're going to be tucking this page and the Settings page into a `Reference` ToC item once both individual PRs are approved.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/f57d85b/mongodb-vscode/docsworker/DOCSP-10236/commands
=> (DOCSP-10236): Add Reference page for all available commands

source/connect.txt, source/index.txt
Added new sub-section under Activate a Connection explaining how once you activate, you can connect the mongodb shell to your deployment.
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker/DOCSP-10907/connect#activate-a-connection
=> (DOCSP-10907): Add info on launching mongodb shell for active deployment

source/playgrounds.txt
New functionality letting you run only a selected portion of a playground.
JIRA: [DOCSP-11269](https://jira.mongodb.org/browse/DOCSP-11269)
Staged: [Run a Playground](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11269/playgrounds#run-a-playground)
=> (DOCSP-11269): Run selected lines from playground

source/index.txt
Staged: [Index Page](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11708/
)
This is a super simple change but have a quick question for review - Should we make it clearer that we're taking them away from the MongoDB docs when they click this link? Would titling the link something like `View Changelog on GitHub` or `Changelog on GitHub` be better?
=> (DOCSP-11708): Add link to changelog

source/databases-collections.txt, source/includes/admonitions/document-search-template.rst, source/read-document-playground.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11550)
[Staged - Navigate Your Data, Documents section](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11550/databases-collections#documents)
[Staged - Read Documents](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11550/read-document-playground)
Created a note about using the search template Playground & put it on the two suggested pages. 
I think this info is best presented as a note because it's straightforward and easily attachable to sections about searching for documents. I don't think there's anything else to cover in a dedicated section because the template is heavily annotated and Playgrounds are already established.
=> (DOCSP-11550) Search for documents with a search template

source/databases-collections.txt
[JIRA](https://github.com/mongodb-js/vscode/pull/161)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11929/databases-collections#indexes)
Added a note that mirrors the tip to search a collection. I think this is the most clear and concise way to present this info given that this small indexes section links off to the server docs for more info about indexes.
As an alternative I considered a full new page under "Explore Your Data with Playgrounds," similar to "Run Aggregation Pipelines." That could be good if we want to really dive into using indexes in playgrounds, but I don't think it's necessary.
=> (DOCSP-11929) Quick index creation with playgrounds

source/playgrounds.txt
Small update explaining new functionality for logging.
Staged: [Log to Console from a Playground](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-12779/playgrounds#log-to-console-from-a-playground)
=> (DOCSP-12779): console.log for playgrounds

source/commands.txt, source/create-document-playground.txt, source/delete-document-playground.txt, source/includes/fact-playground-results.rst, source/includes/run-playground.rst, source/playgrounds.txt, source/read-document-playground.txt, source/run-agg-pipelines.txt, source/update-document-playground.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-13084)
- Stage: 
- [Explore Your Data with Playgrounds](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13084/playgrounds)
- [Create Documents](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13084/create-document-playground)
- [Read Documents](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13084/read-document-playground)
- [Update Documents](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13084/update-document-playground)
- [Delete Documents](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13084/delete-document-playground)
- [Run Aggregation …
=> DOCSP-13084 Display Playground Output in editor

source/export-to-language.txt, source/includes/blank-playground.rst, source/includes/fact-export-options.rst, source/includes/fact-export-selection.rst, source/includes/steps-export-to-language-pipeline.yaml, source/includes/steps-export-to-language-query.yaml, source/includes/steps-open-new-playground.yaml, source/includes/steps-starting-vsce-individual-fields.yaml, source/playgrounds.txt
New VS Code Extension feature that allows exporting playground code to a programming language.
[DOCSP-19772](https://jira.mongodb.org/browse/DOCSP-19772)
[Export a Query or Pipeline to Language](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-19772/export-to-language/)
=> (DOCSP-19772): VSCode export to language

source/includes/steps-atlas-terraform-file-from-template.yaml
Fixing build warning for the deprecated notice on `steps-atlas-terraform-file-from-template.yaml`.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-29912/create-cluster-terraform/#update-the-local-variables
https://jira.mongodb.org/browse/DOCSP-29912
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64639a11df0f8173e92ba482
=> DOCSP-29912 Fix build warning, admonition has been deprecated

source/includes/fact-vsce-preview.rst, source/settings.txt
Removing public preview banner from the settings page.
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-vscode/DOCSP-35013/settings/
https://jira.mongodb.org/browse/DOCSP-35013
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6579bf6a7a5cb5fef5b60143
=> DOCSP-35013 Remove Public Preview on Settings Page

source/playgrounds.txt
- Updated steps to use procedure directive
- Included note on behavior when connection string specifies a default database and how to use a a different one if necessary.
https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-vscode/DOCSP-34836-playgrounds-database-connection-string/playgrounds/#connect-to-a-deployment-from-a-playground
https://jira.mongodb.org/browse/DOCSP-34836
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65738aa37a5cb5fef5487d5a
=> DOCSP-34836 Playgrounds Default DB in Connection String

source/export-to-language.txt
Adding `Go`, `PHP`, and `Rust` to the additional export languages to the VSCode export page.
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-vscode/DOCSP-35991/export-to-language/#export-a-query-or-pipeline-to-language
https://jira.mongodb.org/browse/DOCSP-35991
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b8155e6b2f17c95a905b33
=> DOCSP-35991 Add Additional Export Languages

source/playgrounds.txt
Typo discovered during translation audit.
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/mongodb-vscode/DOCSP-36252/playgrounds/#code-formatting-and-linting-tools
https://jira.mongodb.org/browse/DOCSP-36252
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bd3e9e6b2f17c95a329f31
=> DOCSP-36252: typo fix

source/includes/steps-starting-vsce-individual-fields.yaml
There are `:term:` definitions for replica set on both https://www.mongodb.com/docs/atlas/reference/glossary/ and https://www.mongodb.com/docs/manual/reference/glossary/. When adding intersphinx references to both the manual and atlas snooty throws a warning:
```
ERROR(includes/steps-starting-vsce-individual-fields.yaml:379ish): Ambiguous target: "term:replica set". Locations: https://www.mongodb.com/docs/manual/reference/glossary/#std-term-replica-set, https://www.mongodb.com/docs/atlas/reference/glossary/#std-term-replica-set
```
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-vscode/DOCSP-36256/connect/
https://jira.mongodb.org/browse/DOCSP-36256
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bd5ecd6b2f17c95a41e20f
[What's expected of an …
=> DOCSP-36256 Fix Glossary Warning

source/time-series-collections.txt
Adds documentation for bucketMaxSpanSeconds & bucketRoundingSeconds to the timeseries template
https://preview-mongodbkanchanamongodb.gatsbyjs.io/mongodb-vscode/DOCSP-28039/time-series-collections/#example
https://jira.mongodb.org/browse/DOCSP-28039
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d4fd4c711116598284f846 (clean)
=> DOCSP-28039 add doc for bucketMaxSpanSeconds & bucketRoundingSeconds

source/databases-collections.txt
Adds documentation for new actions in the context menu for documents in the explorer view.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/mongodb-vscode/DOCSP-27021/databases-collections/#view-collection-documents-and-schema
https://jira.mongodb.org/browse/DOCSP-27021
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d4e1bc71111659827980ad (clean)
=> DOCSP-27021 add doc for tree explorer document context menu

source/connect.txt
fix typo reported by linguists working on translation
https://preview-mongodbjwilliamsmongo.gatsbyjs.io/mongodb-vscode/DOCSP-37231/connect/#connect-to-atlas-stream-processing
https://jira.mongodb.org/browse/DOCSP-37231
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e0c08f11db7b04273cf866
- [x ] Is this free of any warnings or errors in the RST?
- [ x] Is this free of spelling errors?
- [x ] Is this free of grammatical errors?
- [ x] Is this free of staging / rendering issues?
- [x ] Are all the links working?
=> DOCSP-37231: translation typo fix

source/create-document-playground.txt, source/crud-ops.txt, source/delete-document-playground.txt, source/playground-databases.txt, source/playgrounds.txt, source/read-document-playground.txt, source/run-agg-pipelines.txt, source/time-series-collections.txt, source/update-document-playground.txt
Adding VSCOde to page titles and defining page labels
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/crud-ops/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/create-document-playground/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/read-document-playground/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/update-document-playground/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/delete-document-playground/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/run-agg-pipelines/
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-vscode/DOCSP-42021/time-series-collections/
https://jira.mongodb.org/browse/DOCSP-42021 …
=> DOCSP-42021 add VSCode to titles

source/commands.txt, source/includes/admonitions/warn-configure-path.rst, source/includes/steps-starting-vsce-connect-with-advanced-connection-settings.yaml, source/settings.txt
Fixed admonitions in tables and examples in tables for VScode. Removed one important admonition.
https://deploy-preview-93--docs-mongodb-vscode.netlify.app/commands/
https://deploy-preview-93--docs-mongodb-vscode.netlify.app/connect/
https://deploy-preview-93--docs-mongodb-vscode.netlify.app/settings/
https://jira.mongodb.org/browse/DOCSP-42971
https://app.netlify.com/sites/docs-mongodb-vscode/deploys/66e8500260612d0008f39fa9
=> DOCSP-42971-vscode-nested-components

source/crud-ops.txt, source/index.txt, source/install.txt, source/playground-databases.txt, source/playgrounds.txt, source/require-playgrounds.txt
Updating ToC labels based on new official style guidelines for the ToC: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/
https://deploy-preview-94--docs-mongodb-vscode.netlify.app
(all labels can be seen through the menu drop-downs)
https://jira.mongodb.org/browse/DOCSP-43307
=> DOCSP-43307-ToC-Refactor

source/ai-data-usage.txt
Updating AI and Data Usage page (wording already approved by legal)
https://deploy-preview-98--docs-mongodb-vscode.netlify.app/ai-data-usage/
https://jira.mongodb.org/browse/DOCSP-44007
=> DOCSP-44007-update-ai-and-data-usage

source/copilot.txt
One of the listed commands says `/query` but it is supposed to be `/schema`. 
https://deploy-preview-100--docs-mongodb-vscode.netlify.app/copilot/
https://jira.mongodb.org/browse/DOCSP-44570
=> DOCSP-44570-incorrect-heading

source/copilot-docs.txt
In the first paragraph of the ['/docs' command page](https://www.mongodb.com/docs/mongodb-vscode/copilot-docs/) under the 'MongoDB Extension for GitHub Copilot' tree, we say "...Copilot uses Retrival-Augmented Generation (RAG)..." – 'retrival' is a typo – this PR changes it to be 'retrieval'.
https://deploy-preview-101--docs-mongodb-vscode.netlify.app/copilot-docs/#-docs-command
https://jira.mongodb.org/browse/DOCSP-44641
=> DOCSP-44641-retrieval-typo

source/copilot-export-test.txt, source/export-to-language.txt
The Export to Language feature is now only available if you enable the copilot extension
https://deploy-preview-104--docs-mongodb-vscode.netlify.app/export-to-language/
https://deploy-preview-104--docs-mongodb-vscode.netlify.app/copilot-export-test/
https://jira.mongodb.org/browse/DOCSP-45571
=> DOCSP-45571-export-to-language-with-copilot

source/settings.txt
Documents the `mdb.presetConnection` setting in VSCode 
https://deploy-preview-106--docs-mongodb-vscode.netlify.app/settings/#settings:~:text=10-,Preset%20Connections,-Specifies%20a%20preset
https://jira.mongodb.org/browse/DOCSP-46639
=> DOCSP-46639 mdb.presetConnection setting
