mongodb/docs-mongodb-vscode

source/includes/steps-open-new-playground.yaml
source/run-agg-pipelines.txt

Adding new page describing how to create Agg Piplines in VSCE
Staged: [Run Aggregation Pipelines](https://docs-mongodbcom-staging.corp.mongodb.com/c74c875/mongodb-vscode/docsworker/DOCSP-9715/run-agg-pipelines)

(DOCSP-9715): VSCE Aggregation Pipelines

---

snooty.toml
source/create-document-playground.txt
source/crud-ops.txt
source/delete-document-playground.txt
source/includes/blank-playground.rst
source/includes/run-playground.rst
source/read-document-playground.txt
source/run-agg-pipelines.txt
source/update-document-playground.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-9714)
Stage
- [Perform CRUD Operations](https://docs-mongodbcom-staging.corp.mongodb.com/6dcbdc2/mongodb-vscode/docsworker/DOCSP-9714/crud-ops)
- [Create Documents](https://docs-mongodbcom-staging.corp.mongodb.com/6dcbdc2/mongodb-vscode/docsworker/DOCSP-9714/create-document-playground)
- [Read Documents](https://docs-mongodbcom-staging.corp.mongodb.com/6dcbdc2/mongodb-vscode/docsworker/DOCSP-9714/read-document-playground)
- [Update Documents](https://docs-mongodbcom-staging.corp.mongodb.com/6dcbdc2/mongodb-vscode/docsworker/DOCSP-9714/update-document-playground)
- [Delete Documents](https://docs-mongodbcom-staging.corp.mongodb.com/6dcbdc2/mongodb-vscode/docsworker/DOCSP-9714/delete-document-playground)

(DOCSP-9714): Perform CRUD Operations in a VSCE Playground

---

source/connect.txt
source/includes/steps-rename-connection.yaml

[JIRA](https://jira.mongodb.org/browse/DOCSP-10378)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/2befcdb/mongodb-vscode/docsworker/DOCSP-10378/connect#rename-a-connection)

(DOCSP-10378): Document Renaming a Connection

---

source/connect.txt
source/create-cluster-terraform.txt
source/includes/list-tables/command-palette-options.rst
source/includes/steps-atlas-terraform-file-from-template.yaml
source/includes/steps-create-atlas-cluster-terraform.yaml
source/includes/steps-delete-atlas-cluster-terraform.yaml
source/includes/terraform-apply-output.sh
source/includes/terraform-init-output.sh
source/includes/terraform-plan-output.sh
source/index.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-10321)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/1444f00/mongodb-vscode/docsworker/DOCSP-10321/create-cluster-terraform)

(DOCSP-10321): Terraform Integration with VSCE

---

source/commands.txt
source/includes/admonitions/configure-path.rst
source/includes/admonitions/warn-configure-path.rst
source/settings.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-10382)
[Staged (commands)](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker/DOCSP-10382/commands#shell-commands)
[Staged (settings)](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker/DOCSP-10382/settings#settings)
Ticket was discussed over Zoom, we decided to include a note about adding the shell to your PATH but not a full set of instructions.

(DOCSP-10382) PATH note

---

source/databases-collections.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-11333)
[Staged section](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-11333/databases-collections#view-collection-documents-and-schema)
Added a line calling attention to the document count.

(DOCSP-11333) Display document count in left navigation panel

---

source/databases-collections.txt

* (DOCSP-11333) Display document count in left navigation panel
* Specify left nav panel
* Update from copy review

(DOCSP-11333) Display document count in left navigation panel (#22)

---

source/playgrounds.txt

- Code lenses are now above the selected code, so I adjusted the docs accordingly
- Code lenses are more links than buttons so I thought I'd adjust the docs. Let me know what you think!

Minor tweaks on code lenses

---

source/databases-collections.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-12721)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-12957/databases-collections)

DOCSP-12957: [VSCODE] Hover over a field name to show a type value written as text

---

source/connect.txt
source/includes/steps-starting-vsce-individual-fields.yaml
source/includes/steps-starting-vsce-paste-string.yaml
source/playgrounds.txt

- [JIRA](https://jira.mongodb.org/browse/DOCSP-13277)
- Stage
- [Connect to Your MongoDB Deployment](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13277/connect#create-a-connection-to-a-deployment)
- [Explore Your Data with Playgrounds](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13277/playgrounds#create-a-new-playground)

DOCSP-13277 Entry points for overview page

---

source/includes/steps-starting-vsce-individual-fields.yaml

- [JIRA](https://jira.mongodb.org/browse/DOCSP-13550)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13550/connect#enter-your-connection-information)

DOCSP-13550 Update hostname inputs in connection form

---

source/playgrounds.txt

@alenakhineika. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-vscode/docsworker-xlarge/DOCSP-13960/playgrounds/)
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=602ffc25ab23346c207bfa8c)

(DOCSP-13960) Add Edit Doc to Playground

---

source/facets.toml

https://jira.mongodb.org/browse/DOCSP-32483
Hey @sarah-olson-mongodb - last one!
Here's the facet.toml file for the vscode repo.  If it looks good to you, please merge!
Thank you for your help!
Sarah

DOCSP-32483 programmatic tagging for vscode repo

---

.github/workflow/vale-tdbx.yml

Set up Vale GitHub action. After this is merged, when we submit pull requests to this repo, the action runs a check and adds PR comments for Vale rule violations.
N/A
N/A
N/A

Set up Vale github action

---

.github/workflows/vale-tdbx.yml

fix vale permission syntax

---

source/databases-collections.txt

Documents insert document context menu action to collections.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/mongodb-vscode/DOCSP-28059/databases-collections/
https://jira.mongodb.org/browse/DOCSP-28059
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65dcd0e87111165982723b90 (clean)

DOCSP-28059 Add insert document context menu action to collections

---

source/copilot.txt

Linking /query to the /query page
https://deploy-preview-95--docs-mongodb-vscode.netlify.app/copilot/#commands
https://jira.mongodb.org/browse/DOCSP-43928

DOCSP-43928-linking-query

---

source/index.txt

Update ToC label to MongoDB Extension for Github Copilot ([per this PR comment](https://github.com/mongodb/docs-mongodb-vscode/pull/96#discussion_r1787963372))
https://deploy-preview-99--docs-mongodb-vscode.netlify.app
https://jira.mongodb.org/browse/DOCSP-44480

DOCSP-44480-copilot-toc-label

---

source/commands.txt

Removes nested "important" admonitions
https://deploy-preview-102--docs-mongodb-vscode.netlify.app/commands/#shell-commands
https://jira.mongodb.org/browse/DOCSP-44796

DOCSP-44796-important-nested-admonitions

---

snooty.toml

Updates site title
None
https://jira.mongodb.org/browse/DOCSP-48295

DOCSP-48295-standardize-titles
